# Generated by Django 4.1.7 on 2023-02-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoarcgis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
