# Generated by Django 4.1.7 on 2023-03-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whoarcgis", "0002_rename_updated_statistic_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistic",
            name="total_vaccinations",
            field=models.IntegerField(default=0),
        ),
    ]
